### ISSUE TITLE
[Feature Request] Date picker as complex user input

### ISSUE THREAD

**Issue by andresrcs** [DillonHammill/DataEditR#11]
Entering dates as text is hard and unreliable, it would be nice to have a calendar that the user can click on to select dates as with `shiny::dateInput()`

**Comment by DillonHammill** [comment]
Done! I added support for password custom columns as well. Pass either `"date"` or `"password"` as an option in `col_options`. - V1 & V2 are names of the columns in the template in this case.
```{r}
data_edit(col_options = list(V1 = "date", V2 = "password")
```

Please pull down the latest version from GitHub:
```{r}
devtools::install_github("DillonHammill/DataEditR")
```

**Comment by andresrcs** [comment]
Great! Thanks!.. As a follow-up, I don't know if this request would make sense for other people but I'm in need of using different input types by row, It would be even possible to implement such functionality? My motive is to be able to use the app on a mobile browser where long tables work better than wide ones.

**Comment by DillonHammill** [comment]
Unfortunately, setting rows types is not supported by rhandsontable. The best you can do is to transpose the data prior to loading the application.

**Comment by andresrcs** [comment]
I use it to save new records to a database, I spread a "date" row as a column before appending the new records to the table on the database, that way I only have to enter the date once but I was hoping to use this new date-picker functionality. Thanks for looking into this anyway.
