### ISSUE TITLE
Shiny Based Installation Error

### ISSUE THREAD

**Issue by gfleetwood** [DillonHammill/DataEditR#13]
Hi. I tried to install the library from CRAN and got this error:

```
Error: object ‘moduleServer’ is not exported by 'namespace:shiny'
Execution halted
```
I checked and that object is not in shiny 1.4.0. Are you using another version? I'm also running R 3.6.0 on Ubuntu 20.04.

**Comment by DillonHammill** [comment]
You will need to update your `shiny`. The latest version on CRAN should be fine:
```{r}
install.packages("shiny")
```

**Comment by DillonHammill** [comment]
With 98bdc42b80e3887fbb4ec94eb7e536bcd0d7e910 I have added a dependency on `shiny 1.0.5` so that it will request an update if your shiny version is too low.
