### ISSUE TITLE
Can not load the data.frame

### ISSUE THREAD

**Issue by jrojasquiroz** [DillonHammill/DataEditR#17]
I had installed the add-in with no problem. But when I tried to open a data frame this message appears:
```
Warning: Error in sub: input string 1 is invalid UTF-8
  51: sub
  50: mysub
  47: trimws
  46: <observer>
   3: shiny::runApp
   2: runGadget
   1: data_edit
```
So, I tried with another one and another similar message appears:
```
Warning: Error in warn: entrada en evaluacion: recursivo por defecto o problemas anteriores?
  67: warn
  66: row.names<-.tbl_df
  64: rownames<-
  63: <reactive>
  47: data_to_edit
  46: <observer>
   3: shiny::runApp
   2: runGadget
   1: data_edit
```

**Comment by DillonHammill** [comment]
Hmmm, looks like there are some non-standard characters in the data.frame. Are you able to share the data so that I can troubleshoot this? You can save the data.frame to an .rds file and share a link?
```{r}
# df is your data.frame
saveRDS(df, "test-data.rds")
```

Can you also provide the printout of `class(df)` prior to using the addin?
