### ISSUE TITLE
Cannot hide upload/download options in Shiny

### ISSUE THREAD

**Issue by towananalytics** [DillonHammill/DataEditR#19]
Firstly - thank you for creating this package, I have been searching for something like this for a long time! It is so easy to use with Shiny!

I have encountered the following minor issue:

`hide = TRUE` argument does not seem to hide the download/upload options when running dataEditServer() directly from shiny.

My app uses a separate download/upload option in a side panel, which works with the DataEditoR to show the uploaded data but I can't seem to disable/suppress the default view from above the table (see attached image).

![table](https://user-images.githubusercontent.com/61938559/118537105-1f5f4900-b77f-11eb-8807-1c8b8fbcbab1.png)

**Comment by DillonHammill** [comment]
It is difficult to help without a reproducible example. Do you have some code you can share?

These UI elements come from the the dataInput module not the dataEdit module. Perhaps you need to pass `hide = TRUE` to `dataInput()`.

**Comment by towananalytics** [comment]
Thanks for the response - I realised that I didn't need the `dataInputServer()` - I'm passing data via another method - which of course removed the highlighted area I showed above...

This is not an issue - thanks again.

**Comment by FilipeamTeixeira** [comment]
Unfortunately I have exactly the same problem here:

`library(DataEditR)
library(shiny)

ui <- fluidPage(
  splitLayout(
    dataInputUI("input1"),
    dataOutputUI("output1"),
    actionButton("done", "Done!"),
    cellWidths = c("60%", "20%", "20%")
  ),
  dataEditUI("edit1")
)

server <- function(input, output, session) {
  
  # DATA INPUT
  data_input <- dataInputServer("input1", hide = TRUE)
  
  # DATA EDIT
  data_update <- dataEditServer("edit1",
                                data = data_input)
  
  # DATA OUTPUT
  dataOutputServer("output1",
                   data = data_update,
                   write_fun = "write.csv",
                   write_args = list(row.names = FALSE))
  

  # DATA RETURN
  observeEvent(input$done, {
    stopApp(data_update())
  })
  
}

shinyApp(ui, server)`
