### ISSUE TITLE
[Feature Request] Text on icon mouseover?

### ISSUE THREAD

**Issue by AndyBunn** [DillonHammill/DataEditR#21]
Would it be possible to have text appear when you mouse over one of the buttons on the editor?

**Comment by DillonHammill** [comment]
@AndyBunn, this is on my list of things to do. It should be pretty straightforward using `shinyBS`.

**Comment by DillonHammill** [comment]
Done! Added to DataEditR v0.1.3 which is available for download from GitHub:
```{r}
devtools::install_github("DillonHammill/DataEditR")
```

![DataEditR 0 1 3](https://user-images.githubusercontent.com/28646736/119583462-081cfd00-be0a-11eb-9bd9-ac615492762c.gif)

**Comment by AndyBunn** [comment]
Thanks!

From: Dillon Hammill ***@***.***>
Reply-To: DillonHammill/DataEditR ***@***.***>
Date: Tuesday, May 25, 2021 at 5:08 PM
To: DillonHammill/DataEditR ***@***.***>
Cc: Andy Bunn ***@***.***>, Mention ***@***.***>
Subject: Re: [DillonHammill/DataEditR] [Feature Request] Text on icon mouseover? (#21)


Done! Added to DataEditR v0.1.3 which is available for download from GitHub:

devtools::install_github("DillonHammill/DataEditR")

[Image removed by sender. DataEditR 0 1 3]<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F28646736%2F119583462-081cfd00-be0a-11eb-9bd9-ac615492762c.gif&data=04%7C01%7Cbunna%40wwu.edu%7Ca8f5bdc5272843349f1808d91fda52c4%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637575844824358207%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=cK2yFkH3cZS9Ht8ydV70D6jPuW91ZpfYLFyP2cL3Kak%3D&reserved=0>
