### ISSUE TITLE
Bug if used within a model

### ISSUE THREAD

**Issue by lgirola** [DillonHammill/DataEditR#25]
Hi, rhandsontable is very useful for the types of models I work with. And in combination with modal dialogue, it makes the model input process very user friendly. 

However, when an rhandsontable is rendered in a modal box, depending on the circumstance only a part of the table is rendered until the user clicks on the partially rendered table. Is this a bug, or am I using rhandsontable incorrectly? Please see super simple MWE code below. It renders the initial table just fine, but when the user makes a change to the table (for example inserting a row with data) and tries re-rendering it by clicking the "Show" action button, only part of the table is rendered until the user clicks on the table.

The first image shows the rendered table when first invoking the app - looks good. The second image shows the rendered table after having inserted a row/data and then clicking "Show" -- I only get a partial rendering of the table until clicking on it, and then the complete table pops up (as it should have done after the "Show" click). The third images shows the completely and correctly rendered table after inserting a 3rd row, after clicking "Show", and after clicking on the partially rendered table.

```
library(shiny)
library(rhandsontable)

ui <- fluidPage(actionButton("show","Show"), 
                actionButton("reset","Reset"))

server <- function(input,output,session){

  dat <- reactiveVal(data.frame(x=runif(2),y=runif(2)))
  
  observeEvent(input$show,{showModal(modalDialog(rHandsontableOutput("hot")))})
  
  observeEvent(input$reset,dat(data.frame(x=runif(2),y=runif(2))))
  
  output$hot <- renderRHandsontable(rhandsontable(dat()))

  } # close Server

shinyApp(ui,server)
```

![Image1](https://user-images.githubusercontent.com/84516599/126863105-2d5e2655-3267-4dcb-888f-0e30a920d3be.png)
![Image2](https://user-images.githubusercontent.com/84516599/126863112-2b4f50fa-4947-4678-97f5-0e23b3cd738c.png)
![Image3](https://user-images.githubusercontent.com/84516599/126863403-14ec121d-6a84-47d3-b6f4-330f6af75376.png)

**Comment by DillonHammill** [comment]
@lgirola, this is a known rhandsontable issue (#24). Please post your issue there https://github.com/jrowen/rhandsontable/issues as there is nothing I can do from the DataEditR side of things to fix this.

**Comment by lgirola** [comment]
Hi Dillon, I tried reposting it correctly this time. I'm not sure I did it right, I'm new to github

Thanks, Lou
-- 
 Sent with Tutanota, the secure & ad-free mailbox. 



Jul 24, 2021, 11:14 by ***@***.***:

**Comment by DillonHammill** [comment]
Thanks!
