### ISSUE TITLE
[Save & Close] button only closes but does not save any changes

### ISSUE THREAD

**Issue by sfd99** [DillonHammill/DataEditR#3]
**_Hi Dillon,_**

    # Make a backup DF m2,  to keep it safe... :-)
     m2  <- mtcars  

    # Open m2  in Rstudio Viewer 
    # and we change some values .ie: mpg from 21 to 2199 
    data_edit( m2 )  

    # Click on the [Save & Close] button
    # and then do:
    head(m2)

See? 
No values have been changed
in  m2 ...

The **[Save & Close]** button
will _close_ the Rstudio Viewer,
but the  m2  data frame
has not been changed any values after the edit...
The m2 values are the same as before.

(I would have expected my value edits
in  m2  to persist after clicking [Save...]).

pls,
 tell me if I misunderstood  something basic. 

thanks, Dillon!
**SFd99**

**Comment by DillonHammill** [comment]
@sfd99, you need to re-assign the output of `data_edit()` to `m2` in order to update the old `m2`:
```{r}
m2 <- data_edit(m2)
head(m2)
```

**Comment by sfd99** [comment]
ok, Dillon, understood.

_Q:_
But then (maybe),
the **[Save & Close]** button
should just say: **[Close]** ?.

just a suggestion... :-)

**Comment by DillonHammill** [comment]
This has now been implemented on the `devel` branch.
```{r}
devtools::install_github("DillonHammill/DataEditR", ref = "devel")
```
![image](https://user-images.githubusercontent.com/28646736/97243231-f494be00-1849-11eb-9c32-fd2ee2a26956.png)

**Comment by mtyszler** [comment]
Hi @DillonHammill ,

I'm still having this problem, using the latest version

If I just click on "Done" changes are lost. Only if I click `sync` it updates. Any hints?

**Comment by sch56** [comment]
Hi @DillonHammill - I really want to know whether the user exited using the Done or the Cancel button. At present there doesn't seem to be any way to do this if they haven't actually changed some data.
Would it make sense to not return the data when the Cancel is pressed?
Or is there another way of determining this from the calling process? 

The scenario for me is:
1. Get some data
2. Make some proposed changes
3. Use DataEditR for user to review or adjust
4. Either proceed with the (adjusted) changes (Done) or back out and start again (Cancel).

At present I can't distinguish 'Done' with no change from 'Cancel' - meaning back out.

**Comment by iamihgam** [comment]
The results are not saved with any button. The whole purpose of editing is wasted
