### ISSUE TITLE
Data Not Saving

### ISSUE THREAD

**Issue by dcmg21** [DillonHammill/DataEditR#45]
When trying to save edits to a new dataframe nothing saves.  Are you supposed to just hit done?

**Comment by DillonHammill** [comment]
@dcmg21 you need to hit the sync button before saving in order to keep your changes.

**Comment by dcmg21** [comment]
@DillonHammill and when clicking Done that will save the changes?

**Comment by DillonHammill** [comment]
Yes, hitting done simply returns the edited copy of the data. If you don't hit `sync` it will return the original copy of the data. This is only temporary, in future updates the `sync` will be removed.
