### ISSUE TITLE
yeti is not an available theme

### ISSUE THREAD

**Issue by palmersg58** [DillonHammill/DataEditR#47]
When I try to run data_edit() I get the error message:

Error in shinytheme(theme) : 
  yeti is not an available theme. Valid themes are: .

I cannot find any guidance to fix this error.

Are you able to help?

**Comment by DillonHammill** [comment]
I have just pushed a fix to GitHub, see #46. Please install the development version from GitHub:
```{r}
devtools::install_github("DillonHammill/DataEditR")
```
These changes will appear on CRAN in the next couple of days.

**Comment by palmersg58** [comment]
Thank you for getting back to me so fast.

Everything appears to work now.


Ngā mihi



Dr Stephen Palmer | Medical Officer of Health | Regional Public Health

Phone (04) 570 9132
Mobile (0)27 430 6402
www.rph.org.nz<http://www.rph.org.nz/>


***@***.***



[http://i1.cmail19.com/ei/d/E3/34A/71D/061144/csfinal/COVID_Signature_RPH-9900000000079e3c.jpg]

________________________________
