### ISSUE TITLE
[feature request] filter, order and arrange options

### ISSUE THREAD

**Issue by vorpalvorpal** [DillonHammill/DataEditR#6]
Thanks for the great project.

I was wondering if you would be interested in implementing any manipulations of the data. View() allows you to reorder and filter rows by a particular column. This would be quite useful to allow users to better explore and edit the data. For example, I want to edit the values of column 1 only where the value of column 2 is greater than x. 

Potentially re-ordering columns might also be useful.

If you think this would be useful, the question would be, should the filtering/ordering/arranging be saved or not. It would be easy to filter a column, do some editing and click save without remembering to remove the filter. This would end up with you losing filtered out rows. Equally, however, there would no doubt be use cases where you want the user to be able to filter rows and then return the smaller filtered data frame...

**Comment by DillonHammill** [comment]
@vorpalvorpal, now that DataEditR uses a modular design (available on the `devel` branch), it should be possible to add support for such operations. There will be a few things that will need to be figured out:

- These operations will need to be performed independently of `rhandsontable` as any call to `hot_cols()` will mess around with other data editing capabilities. Furthermore, as far as I know `rhandsontable` only supports sorting of numeric columns.
- Based on the above point, this means that we could write `dataSort` and `dataFilter` modules to handle these operations. The major question would be what should the UI look like? The reason this is not currently implemented is to maximize the space available to display the data for editing - adding additional UI elements will require more scrolling to view the data.
- To maximize available space, I will need to add arguments to `data_edit()` to allow control over which modules to include in the application (e.g. logical arguments `input`, `output`, `edit`, `sort` and `filter`).
- There will also be additional complexity in getting the modules to appropriately communicate with one another, for example if you edit a filtered dataset but want to update the entire dataset as well. 
- Changing column order is supported by `rhandsontable` but has been deliberately turned off for now as it adds another layer of complexity when converting interactive edits into code (still a work in progress). However, I think it may be possible to add back support for this if I simply compare the output data to the original data and convert this into code.

The key will be in designing an appropriate and minimalist UI to support these operations - I will think about and see if I can come up with something that will work.

**Comment by vorpalvorpal** [comment]
That's a good point about the UI. I hadn't really thought about that.

**Comment by DillonHammill** [comment]
@vorpalvorpal, I just realised that you can actually filter the data by typing in the filtering steps into the `data` field. For example, if you only wanted to extract/view/edit only the `setosa` species in `iris` dataset:
![DataEditR-Filter](https://user-images.githubusercontent.com/28646736/97513403-453e1f80-19e0-11eb-9f0f-621bdd83a8aa.gif)
This also means that you can do things like `head(iris)` and `tail(iris)` to look at the top and bottom rows of the data.

**Comment by DillonHammill** [comment]
@vorpalvorpal I have added column selection and row filtering modules to the new version of DataEditR that is now available on GitHub. 
```{r}
devtools::install_github("DillonHammill/DataEditR")
```

**Comment by vorpalvorpal** [comment]
I just checked it out. Looks awesome! You're a champion.
